//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kres_Basvuru_Form
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kres_BasvuruEntities4 : DbContext
    {
        public Kres_BasvuruEntities4()
            : base("name=Kres_BasvuruEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anne_Bilgisi> Anne_Bilgisi { get; set; }
        public virtual DbSet<Baba_Bilgisi> Baba_Bilgisi { get; set; }
        public virtual DbSet<Bakanin_Bilgisi> Bakanin_Bilgisi { get; set; }
        public virtual DbSet<Basvuranin_Bilgisi> Basvuranin_Bilgisi { get; set; }
        public virtual DbSet<Cocuk_Bilgisi> Cocuk_Bilgisi { get; set; }
        public virtual DbSet<Cocuk_Harici_Bilgi> Cocuk_Harici_Bilgi { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
